name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.actor }}/deploy-pypi/deploy-pypi
          tags: latest,${{ github.ref }}
          password: ${{ github.token }}
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
